local planet_priorities = { "current", "nauvis", "vulcanus", "fulgora", "gleba", "aquilo" }

data:extend({
	{
		type = "bool-setting",
		name = "ipl-force-enabled",
		setting_type = "runtime-per-user",
		default_value = false,
		order = "aa",
	},
	{
		type = "bool-setting",
		name = "ipl-trash-enabled",
		setting_type = "runtime-per-user",
		default_value = true,
		order = "ba",
	},
	{
		type = "string-setting",
		name = "ipl-trash-priority",
		setting_type = "runtime-per-user",
		default_value = "current",
		allowed_values = planet_priorities,
		order = "bb",
	},
	{
		type = "bool-setting",
		name = "ipl-request-enabled",
		setting_type = "runtime-per-user",
		default_value = true,
		order = "ca",
	},
	{
		type = "string-setting",
		name = "ipl-request-priority",
		setting_type = "runtime-per-user",
		default_value = "current",
		allowed_values = planet_priorities,
		order = "cb",
	},
	{
		type = "bool-setting",
		name = "ipl-delete-trash-overflow",
		setting_type = "runtime-per-user",
		default_value = false,
		order = "da",
	},
	{
		type = "bool-setting",
		name = "ipl-notify-full",
		setting_type = "runtime-per-user",
		default_value = true,
		order = "db",
	},
	{
		type = "string-setting",
		name = "ipl-transfer-mode",
		setting_type = "runtime-global",
		default_value = "local",
		allowed_values = { "local", "planetary", "interplanetary" },
		order = "dc",
	},
	{
		type = "int-setting",
		name = "ipl-ticks-per-transfer",
		setting_type = "runtime-global",
		default_value = 60,
		minimum_value = 1,
		order = "de",
	},
})
